name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Clippy
        run: nix develop -c cargo clippy --all-targets --all-features
      - name: fmt
        run: nix develop -c cargo fmt --check
      - name: test
        run: nix develop -c cargo test --all-features
      - name: miri
        run: nix develop -c cargo miri test --all-features

